# Generated by Django 5.0.6 on 2024-07-14 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_room_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='services',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out')], default='booked', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Phasellus vestibulum lorem sed risus ultricies. Enim nunc faucibus a pellentesque sit. Dui id ornare arcu odio ut. Quis varius quam quisque id diam. Dictum non consectetur a erat nam at lectus. Risus quis varius quam quisque id diam vel quam elementum. Proin fermentum leo vel orci porta. Consequat mauris nunc congue nisi vitae. Pellentesque elit ullamcorper dignissim cras tincidunt. Aliquam malesuada bibendum arcu vitae elementum. Leo a diam sollicitudin tempor id. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo. Quis auctor elit sed vulputate. Ultricies leo integer malesuada nunc vel risus. Cursus sit amet dictum sit amet justo. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Tellus integer feugiat scelerisque varius morbi enim. Feugiat scelerisque varius morbi enim nunc faucibus.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, upload_to='room_images/'),
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, default=700, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_reviews', to='bookings.room'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('laundry', 'Laundry'), ('food_service', 'Food Service'), ('room_cleaning', 'Room Cleaning')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
            ],
        ),
    ]
