# Generated by Django 5.0.6 on 2024-07-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_rename_price_room_cost_rename_price_service_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Suite', 'Suite'), ('Family', 'Family'), ('Economy', 'Economy')], max_length=20),
        ),
    ]
