# Generated by Django 5.0.6 on 2024-07-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('suite', 'Suite'), ('family', 'Family'), ('economy', 'Economy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.BooleanField(choices=[('laundry', 'Laundry'), ('food_service', 'Food Service'), ('room_cleaning', 'Room Cleaning')], max_length=50),
        ),
    ]
