# Generated by Django 5.0.6 on 2024-07-20 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_roomtype_alter_room_room_type'),
    ]

    operations = [
    ]
