# Generated by Django 5.0.6 on 2024-07-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_modified_booking_time_review_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default='John Doe', max_length=80),
            preserve_default=False,
        ),
    ]
