# Generated by Django 5.0.6 on 2024-10-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_review_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
