# Generated by Django 5.0.6 on 2024-10-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_alter_customeruser_email_alter_customeruser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
