import Image from "next/image";
import bg from '../images/hero/bg.jpg'
const About = () => {
    return (
      <div className="container mx-auto px-4 py-16">
        <div>
          <title>About Us</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </div>
  
        {/* <h1 className="text-4xl font-bold text-center mb-8">ABOUT US</h1>
  
        <p className="text-lg text-gray-600 text-center mb-12">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus
          incidunt odio quos dolore commodi repudiandae tenetur consequuntur et
          similique asperiores.
        </p> */}
  
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div>
            <h2 className="text-2xl font-bold mb-4">Welcome to Our Hotel</h2>
            <p className="text-lg text-gray-600">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Iaculis at erat pellentesque adipiscing commodo. Integer feugiat scelerisque varius morbi enim nunc faucibus a pellentesque. Aliquam vestibulum morbi blandit cursus risus at. Velit scelerisque in dictum non consectetur a erat nam. Venenatis cras sed felis eget. Vitae elementum curabitur vitae nunc sed. Varius morbi enim nunc faucibus a pellentesque sit amet porttitor. Pellentesque elit eget gravida cum sociis natoque. Neque aliquam vestibulum morbi blandit cursus risus at ultrices. Nam libero justo laoreet sit. Aenean euismod elementum nisi quis eleifend quam adipiscing. Quis viverra nibh cras pulvinar mattis nunc sed blandit libero. Eget nunc scelerisque viverra mauris in aliquam sem. Mi eget mauris pharetra et ultrices neque ornare aenean euismod. Tellus at urna condimentum mattis pellentesque id nibh tortor id.
            </p>
          </div>
          <div>
          <Image src={bg} alt="Placeholder Person" className="rounded-lg shadow-md" 
          />  
            
          </div>
        </div>
      </div>
    );
}

export default About;
